<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-25JO6U9" failures="1" tests="6" name="practice.RetryAnalyszerTest" time="0.029" errors="0" timestamp="2025-04-01T10:39:39 IST" skipped="5">
  <testcase classname="practice.RetryAnalyszerTest" name="activateSim" time="0.001">
    <skipped/>
  </testcase> <!-- activateSim -->
  <testcase classname="practice.RetryAnalyszerTest" name="activateSim" time="0.001">
    <skipped/>
  </testcase> <!-- activateSim -->
  <testcase classname="practice.RetryAnalyszerTest" name="activateSim" time="0.021">
    <skipped/>
  </testcase> <!-- activateSim -->
  <testcase classname="practice.RetryAnalyszerTest" name="activateSim" time="0.003">
    <skipped/>
  </testcase> <!-- activateSim -->
  <testcase classname="practice.RetryAnalyszerTest" name="activateSim" time="0.001">
    <skipped/>
  </testcase> <!-- activateSim -->
  <testcase classname="practice.RetryAnalyszerTest" name="activateSim" time="0.002">
    <failure message="expected [c] but found [x]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [c] but found [x]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at practice.RetryAnalyszerTest.activateSim(RetryAnalyszerTest.java:11)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- activateSim -->
</testsuite> <!-- practice.RetryAnalyszerTest -->
